### ISSUE TITLE
Установка

### ISSUE THREAD

**Issue by nlotambov** [AlexanderPro29/OctoPrint-RU-LangPack#1]
Привет, как установить?

**Comment by AlexanderPro29** [comment]
Привет! Скачать архив с переводом OctoPrint-*.zip с этого сайта. Открыть вэб-интерфейс OctoPrint, настройки (нажать ключик вверху), выбрать "Appearance" в левом списке, нажать кнопку "Manage" в строке "Language Packs", далее после строки "Upload additional Language Packs" нажать на "Browse" и выбрать скачанный ранее архив. Нажать "Upload". Затем "Close". После перезагрузки OctoPrint должен автоматически переключиться на русский, нажать Ctrl+F5 также будет не лишним. Там же в настройках в строке "Default Language" после перезагрузки сервера можно выбрать появившийся русский язык, если автоматически не переключается.
