### ISSUE TITLE
Слишком длинный текст. Форма съезжает.

### ISSUE THREAD

**Issue by EagleB3** [AlexanderPro29/OctoPrint-RU-LangPack#3]
Подсократить бы, а то форма съезжает:
"Модификатор скорости подачи",
"Подать пластик",
"Втянуть пластик",
"Модификатор потока"
![Слишком широко](https://user-images.githubusercontent.com/43371261/101051817-f105fc80-3596-11eb-8476-96bb74d8218c.png)

![Сравнение экрана](https://user-images.githubusercontent.com/43371261/101052287-7f7a7e00-3597-11eb-939b-0ac8cff283e9.png)

Предлагаю в качестве вариантов:
"Коэф.подачи", или "Множ.подачи"
"Выдать",
"Втянуть",
"Коэф.потока", или "Множ.потока"

P.S. И большое спасибо за языковый пакет!

**Comment by AlexanderPro29** [comment]
Внес изменения в последнем релизе. Причина съезжания оказалась совершенно в другом месте, но сейчас должно нормально отображаться.

**Comment by EagleB3** [comment]
Огромное спасибо!
Все просто превосходно!
![OK](https://user-images.githubusercontent.com/43371261/102516308-c0968600-409f-11eb-9ad6-efe79f552e9f.png)
