### ISSUE TITLE
Названия меню и некоторый текст на английском в OctoPrint 1.8.0 и старше

### ISSUE THREAD

**Issue by AlexDashwood** [AlexanderPro29/OctoPrint-RU-LangPack#4]
В новых версиях октопринта (1.8.0+) пункты меню и некоторый текст (например, сообщение при нажатие на "Перезагрузить") показываются на английском, вместо русского. В октопринте 1.7.3 все вышеперечисленное на русском.
Использовал актуальный русификатор "RU LangPack for OctoPrint 1.7.3+", который значится для "версии 1.7.3 и новее".

Прикладываю скриншоты двух версий октопринта: с зелёным фоном "старая" 1.7.3 и с синим фоном "новая" 1.8.1:

![_20220707_111419](https://user-images.githubusercontent.com/105418634/177730550-b51353b1-700b-456f-95a2-754add3a4f0f.JPG)
![_20220707_111453](https://user-images.githubusercontent.com/105418634/177730586-8c36cd2f-95ac-4742-a431-b0e6f2d8a9e1.JPG)
![_20220707_111518](https://user-images.githubusercontent.com/105418634/177730625-7d2e2e92-f9cb-485c-b73f-4e46091d1930.JPG)
![_20220707_111557](https://user-images.githubusercontent.com/105418634/177730662-5efec869-f607-4c35-9e50-b4e2e30b2f54.JPG)
![_20220707_112100](https://user-images.githubusercontent.com/105418634/177730691-e8c854aa-f37b-43a9-9acf-88f59aa54fa4.JPG)
![_20220707_111842](https://user-images.githubusercontent.com/105418634/177730730-73d2c1d8-5cb1-41e3-9158-e2e60e2aae6c.JPG)

**Comment by AlexanderPro29** [comment]
Разработчики Octoprint постоянно вносят некоторые изменения в текстах в новых версиях, поэтому бывает перевод в этих местах слетает. Пометка "для версии 1.7.3 и новее" означает, что на более старых версиях перевод точно будет глючить, так как он собирался на новейшей на тот момент версии 1.7.3. В более новых версиях просто будет отсутствовать перевод в добавленных вновь или измененных текстах. Я занимаюсь этим переводом только в свое свободное время, поэтому обновления языкового пакета выходят нерегулярно.

**Comment by AlexanderPro29** [comment]
Сегодня я сделал новый пак для актуальной версии 1.8.6, доступно в Релизах.
